# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EMG.ui'
#
# Created: Sun Mar 11 18:54:16 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import pyqtgraph as pg

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 770)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 480, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 510, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.kelamin = QtGui.QComboBox(self.centralwidget)
        self.kelamin.setGeometry(QtCore.QRect(210, 540, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(10)
        self.kelamin.setFont(font)
        self.kelamin.setObjectName(_fromUtf8("kelamin"))
        self.kelamin.addItem(_fromUtf8(""))
        self.kelamin.addItem(_fromUtf8(""))
        self.RECORD = QtGui.QPushButton(self.centralwidget)
        self.RECORD.setGeometry(QtCore.QRect(490, 600, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.RECORD.setFont(font)
        self.RECORD.setObjectName(_fromUtf8("RECORD"))
        self.Channel_Otot = QtGui.QGroupBox(self.centralwidget)
        self.Channel_Otot.setGeometry(QtCore.QRect(800, 460, 431, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Channel_Otot.setFont(font)
        self.Channel_Otot.setObjectName(_fromUtf8("Channel_Otot"))
        self.Channel_4 = QtGui.QComboBox(self.Channel_Otot)
        self.Channel_4.setGeometry(QtCore.QRect(260, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel_4.setFont(font)
        self.Channel_4.setObjectName(_fromUtf8("Channel_4"))
        self.Channel_4.addItem(_fromUtf8(""))
        self.Channel_4.addItem(_fromUtf8(""))
        self.Channel_4.addItem(_fromUtf8(""))
        self.Channel_4.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.Channel_Otot)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.Channel_2 = QtGui.QComboBox(self.Channel_Otot)
        self.Channel_2.setGeometry(QtCore.QRect(260, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel_2.setFont(font)
        self.Channel_2.setObjectName(_fromUtf8("Channel_2"))
        self.Channel_2.addItem(_fromUtf8(""))
        self.Channel_2.addItem(_fromUtf8(""))
        self.Channel_2.addItem(_fromUtf8(""))
        self.Channel_2.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.Channel_Otot)
        self.label_7.setGeometry(QtCore.QRect(30, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Channel_3 = QtGui.QComboBox(self.Channel_Otot)
        self.Channel_3.setGeometry(QtCore.QRect(260, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel_3.setFont(font)
        self.Channel_3.setObjectName(_fromUtf8("Channel_3"))
        self.Channel_3.addItem(_fromUtf8(""))
        self.Channel_3.addItem(_fromUtf8(""))
        self.Channel_3.addItem(_fromUtf8(""))
        self.Channel_3.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.Channel_Otot)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.Channel_1 = QtGui.QComboBox(self.Channel_Otot)
        self.Channel_1.setGeometry(QtCore.QRect(260, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Channel_1.setFont(font)
        self.Channel_1.setObjectName(_fromUtf8("Channel_1"))
        self.Channel_1.addItem(_fromUtf8(""))
        self.Channel_1.addItem(_fromUtf8(""))
        self.Channel_1.addItem(_fromUtf8(""))
        self.Channel_1.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.Channel_Otot)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.usia = QtGui.QSpinBox(self.centralwidget)
        self.usia.setGeometry(QtCore.QRect(210, 510, 51, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(10)
        self.usia.setFont(font)
        self.usia.setMaximum(120)
        self.usia.setObjectName(_fromUtf8("usia"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 540, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Start = QtGui.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(120, 600, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.Start.setFont(font)
        self.Start.setObjectName(_fromUtf8("Start"))
        self.STOP = QtGui.QPushButton(self.centralwidget)
        self.STOP.setGeometry(QtCore.QRect(330, 600, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.STOP.setFont(font)
        self.STOP.setObjectName(_fromUtf8("STOP"))
        self.nama = QtGui.QLineEdit(self.centralwidget)
        self.nama.setGeometry(QtCore.QRect(210, 480, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("STXinwei"))
        font.setPointSize(15)
        self.nama.setFont(font)
        self.nama.setObjectName(_fromUtf8("nama"))
        self.win_1 = pg.GraphicsWindow()

        self.win_2 = pg.GraphicsWindow()
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1351, 451))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Channel_Genap = QtGui.QHBoxLayout()
        self.Channel_Genap.setObjectName(_fromUtf8("Channel_Genap"))
        self.Channel_Genap.addWidget(self.win_1)
        self.horizontalLayout.addLayout(self.Channel_Genap)
        self.Channel_Ganjil = QtGui.QHBoxLayout()
        self.Channel_Ganjil.setObjectName(_fromUtf8("Channel_Ganjil"))
        self.Channel_Ganjil.addWidget(self.win_2)
        self.horizontalLayout.addLayout(self.Channel_Ganjil)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ELECTROMYOGRAPHY", None))
        self.label.setText(_translate("MainWindow", "NAMA", None))
        self.label_2.setText(_translate("MainWindow", "USIA", None))
        self.kelamin.setItemText(0, _translate("MainWindow", "Laki-Laki", None))
        self.kelamin.setItemText(1, _translate("MainWindow", "Perempuan", None))
        self.RECORD.setText(_translate("MainWindow", "RECORD", None))
        self.Channel_Otot.setTitle(_translate("MainWindow", "Channel Otot", None))
        self.Channel_4.setItemText(0, _translate("MainWindow", "m. Biceps brachii", None))
        self.Channel_4.setItemText(1, _translate("MainWindow", "m. Triceps brachii", None))
        self.Channel_4.setItemText(2, _translate("MainWindow", "m. Deltoid posterior", None))
        self.Channel_4.setItemText(3, _translate("MainWindow", "m. Deltoid anterior", None))
        self.label_4.setText(_translate("MainWindow", "Channel 1", None))
        self.Channel_2.setItemText(0, _translate("MainWindow", "m. Biceps brachii", None))
        self.Channel_2.setItemText(1, _translate("MainWindow", "m. Triceps brachii", None))
        self.Channel_2.setItemText(2, _translate("MainWindow", "m. Deltoid posterior", None))
        self.Channel_2.setItemText(3, _translate("MainWindow", "m. Deltoid anterior", None))
        self.label_7.setText(_translate("MainWindow", "Channel 4", None))
        self.Channel_3.setItemText(0, _translate("MainWindow", "m. Biceps brachii", None))
        self.Channel_3.setItemText(1, _translate("MainWindow", "m. Triceps brachii", None))
        self.Channel_3.setItemText(2, _translate("MainWindow", "m. Deltoid posterior", None))
        self.Channel_3.setItemText(3, _translate("MainWindow", "m. Deltoid anterior", None))
        self.label_6.setText(_translate("MainWindow", "Channel 3", None))
        self.Channel_1.setItemText(0, _translate("MainWindow", "m. Biceps brachii", None))
        self.Channel_1.setItemText(1, _translate("MainWindow", "m. Triceps brachii", None))
        self.Channel_1.setItemText(2, _translate("MainWindow", "m. Deltoid posterior", None))
        self.Channel_1.setItemText(3, _translate("MainWindow", "m. Deltoid anterior", None))
        self.label_5.setText(_translate("MainWindow", "Channel 2", None))
        self.label_3.setText(_translate("MainWindow", "JENIS KELAMIN", None))
        self.Start.setText(_translate("MainWindow", "START", None))
        self.STOP.setText(_translate("MainWindow", "STOP", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

